### PR TITLE
Robustify

### PR DESCRIPTION
**Pull request by nhammond**
Reduce errors related to:
- Dropped database connections
- Concurrent modification
- Long-running or multipart asynchronous tasks
Add model validation whenever saving django models

### CODE REVIEW

**Comment by nhammond** [comment]
Following up with a bugfix and another pull request

**Comment by nhammond** [comment]
Reopening. Looks like the last commit is included in the PR even though it went in late.

**Comment by nhammond** [comment]
Overview of changes.

bin/run.master.sh
Doubled number of gunicorn workers. This is because sometimes I was getting 502 Bad Gateway errors at peak load. Haven’t seen it since the change.

loomengine/client/playbooks/templates/nginx.conf
loomengine/client/playbooks/vars/common.yml
loomengine/client/settings/gcloud.conf
loomengine/client/settings/local.conf
Revert to NGINX docker container’s default logging. In the Dockerfile they link /var/log/nginx.xx to /dev/stdout, so NGINX logs to a file but it shows up in the Docker container’s stdout, and that’s the behavior we want.

loomengine/master/__init__.py
Because in Django having loomengine.master.api.x and api.x both on the path causes conflicts sometimes. You’re not supposed to have an __init__.py in the root project dir. This always shows up when I’m running tests interactively with “manage.py test”.

loomengine/master/api/tasks.py -> async.py
Double use of tasks for both database models and celery tasks is confusing. This file contains all of our celery tasks.
Biggest change in this PR is removing async.process_active_step_runs. We used to scan all open StepRuns every 30 seconds to see if there were new tasks to be created. Now we just check when new data arrives, and it’s a narrow check for tasks that that data could go into. That change reduces asynchronous task activity by a lot, and it gets rid of the annoying <= 30 second delay between steps.
Moved “kill_task_attempt” to async. Previously it was done in a loop, e.g. for t in task_attempts, t.kill(). That means if the first one fails, all the others get skipped. This change protects against that. It should also reduces lag time on killing tasks (although since we don’t have a priority queue yet for async tasks, lag time can also be made worse by sending stuff to the back of the line at peak times).

loomengine/master/api/models/base.py
Consolidated some redundant code in the FilterHelper
Changed save method to do model validation with full_clean(). That enforces validators that we create on our django models. This was useful since it turned up quite a few cases of invalid data going to the database. The alternative would be to call full_clean before we call save everywhere in the code base, which might be preferred because it avoids calling validators when internal Django methods call save. I just created a ticket for that (#339).  

setattrs_and_save_with_retries is a new method that protects against ConcurrentModificationError. In general when you hit that error it’s ok to make the edits, but you don’t want to overwrite the whole model. This method does a few retries where it reloads the model and edits just the fields you wanted to change before trying to save again. This has eliminated a bunch of sporadic errors.

loomengine/master/api/models/data_objects.py
You’ll see a lot of “blank=true” settings on model fields that allow null in the database. That affects Django’s model validation, which is necessary now that our “save” method is calling “full_clean”.

There are also changes to how we process FileDataObjects. There were some magic methods before, where saving a file used signals to call a postsave method that created a FileResource. I’ve gone toward a more explicit workflow where the client has to give an instruction to create_file_resource.

loomengine/master/api/models/data_trees.py
The only significant change is the push_all and push_by_index methods. “index” refers to a data object’s position in a tree. When a new run is created, push_all is used to check for tasks that can be generated with that data. push_by_index checks only for tasks at that index. This mechanism is what replaces the “async.process_all_active_step_runs” method that used to run on a schedule.

(That tree represents a nested structure  that supports parallel runs. Think of a list of lists, [[a,b], [c,d]], so the index of c would be [1,0]. Maybe the downstream step is going to “gather”, meaning accept an array input, but still iterate over the outer list, so it will run once with [a,b], and once with [c,d].)

loomengine/master/api/models/input_nodes.py
Moved InputNodeSet to tasks.py, since that is the only place it is being used.

loomengine/master/api/models/tasks.py
restart method needs some work. Successful runs were timing out by accident and being killed and rerun. Removed the method for now.
Added “index” to task_runs. That index corresponds to the index in the data tree, with adjustments for scatter/gather. Currently just running scalar, but the data structures are in place to move to parallel.
Changes to post_save/initialize_file are analogous to changes on FileDataObject. No more magic signals. Client has to explicitly request to create a FileDataObject on a TaskLog.

loomengine/master/api/models/templates.py
Stubbed out validators to be completed later.

loomengine/master/api/serializers/data_objects.py
Changes in view_names are related to the new APIDoc. To document all the data types, they each get their own set of API endpoints, in addition to a common endpoint that handles any data type. This view_name determines the value for the ‘url’ field in the serialized data. Now it sends you to the object-specific endpoint instead of the generic one.

loomengine/master/api/serializers/tasks.py
We were using atomic transactions in a few places before, not consistently. I removed these out of concerns for database performance on long-running tasks.

loomengine/master/api/test/*
Some refactoring, and some tests for models/base.py

loomengine/master/api/urls.py
loomengine/master/api/views.py
loomengine/utils/connection.py
New support for endpoints to create FileDataObject on TaskLog and FileResource on FileDataObject.

**Comment by isaacliao** [comment]
Nice, thanks for the summary of changes! Made it much easier to understand.

**Pull request merged**
